# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_auto_20170909_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentbookmark',
            name='comments_per_page',
        ),
    ]
