# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('color', models.CharField(blank=True, help_text='Title color in hex format (i.e: #1aafd0).', max_length=7, verbose_name='color')),
                ('reindex_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified at')),
                ('is_global', models.BooleanField(default=True, help_text='Determines whether the topics will bedisplayed in the all-categories list.', verbose_name='global')),
                ('is_closed', models.BooleanField(default=False, verbose_name='closed')),
                ('is_removed', models.BooleanField(default=False, verbose_name='removed')),
                ('is_private', models.BooleanField(default=False, verbose_name='private')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='category parent')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['title', 'pk'],
            },
        ),
    ]
