# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 01:15
from __future__ import unicode_literals

from django.db import migrations
import utils.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=utils.model_fields.AutoSlugField(blank=True, db_index=False, populate_from='title'),
        ),
    ]
