# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment', '0002_auto_20170903_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_html', models.TextField(verbose_name='comment html')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Comment', verbose_name='original comment')),
            ],
            options={
                'verbose_name': 'comment history',
                'verbose_name_plural': 'comments history',
                'ordering': ['-date', '-pk'],
            },
        ),
    ]
