# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 20:10
from __future__ import unicode_literals

from django.db import migrations
import utils.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_auto_20170905_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='post',
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=utils.model_fields.AutoSlugField(blank=True, db_index=False, populate_from='title'),
        ),
    ]
