# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='Facebook profile url'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grad_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='Twitter handle'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website_link',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='Personal website url'),
        ),
    ]
