# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 06:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170906_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=utils.models.AutoSlugField(blank=True, db_index=False, populate_from='user.username'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='profile'),
        ),
    ]
