# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentpoll',
            options={'ordering': ['pk'], 'verbose_name': 'comment poll', 'verbose_name_plural': 'comments polls'},
        ),
    ]
