# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20170906_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=8300, verbose_name='comment'),
        ),
    ]
