# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20170912_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date', '-pk'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
